sudo: false
language: python
python: 3.5
install: pip install tox coveralls wheel
script: tox -e $TOXENV
env:
  - TOXENV=py27-django-110
  - TOXENV=py34-django-110
  - TOXENV=py35-django-110
  - TOXENV=py27-django-19
  - TOXENV=py34-django-19
  - TOXENV=py35-django-19
  - TOXENV=py27-django-18
  - TOXENV=py35-django-18
  - TOXENV=py27-django-17
  - TOXENV=py27-lint
  - TOXENV=sphinx
  - TOXENV=readme
after_success: coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a6b1ff8e37f14306d32
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
