sudo: false
language: python
install: pip install tox coveralls wheel
script: tox -vv
env:
  - TOXENV=py27-django-17
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py35-django-18
  - TOXENV=py35-django-19
after_success: coveralls
